/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author alunos
 */
public class Inicio_GUI extends javax.swing.JFrame {

    /**
     * Creates new form Inicio_GUI
     */
    public Inicio_GUI() {
        initComponents();
        View.Inicio_GUI.abaixo_peso.setVisible(false);
        View.Inicio_GUI.normal.setVisible(false);
        View.Inicio_GUI.sobrepeso.setVisible(false);
        View.Inicio_GUI.obesidade_leve.setVisible(false);
        View.Inicio_GUI.obesidade_moderada.setVisible(false);
        View.Inicio_GUI.obesidade_morbida.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        altura = new javax.swing.JTextField();
        peso = new javax.swing.JTextField();
        calcular_imc = new javax.swing.JButton();
        closeBTN = new javax.swing.JButton();
        normal = new javax.swing.JLabel();
        sobrepeso = new javax.swing.JLabel();
        obesidade_leve = new javax.swing.JLabel();
        abaixo_peso = new javax.swing.JLabel();
        obesidade_moderada = new javax.swing.JLabel();
        obesidade_morbida = new javax.swing.JLabel();
        valorImc = new javax.swing.JLabel();
        clean_btn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(102, 102, 102), 2));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel1.setText("Calculadora IMC");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel2.setText("Altura:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 90, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jLabel3.setText("Peso:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        altura.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                alturaActionPerformed(evt);
            }
        });
        jPanel1.add(altura, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 120, 154, 40));

        peso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pesoActionPerformed(evt);
            }
        });
        jPanel1.add(peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 120, 146, 40));

        calcular_imc.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        calcular_imc.setText("Calcular");
        calcular_imc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                calcular_imcActionPerformed(evt);
            }
        });
        jPanel1.add(calcular_imc, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 80, 290, 40));

        closeBTN.setText("Fechar");
        closeBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closeBTNActionPerformed(evt);
            }
        });
        jPanel1.add(closeBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 20, -1, -1));

        normal.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 2.png"))); // NOI18N
        jPanel1.add(normal, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        sobrepeso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 3.png"))); // NOI18N
        jPanel1.add(sobrepeso, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 200, -1, -1));

        obesidade_leve.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 4.png"))); // NOI18N
        jPanel1.add(obesidade_leve, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 210, -1, -1));

        abaixo_peso.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 1.png"))); // NOI18N
        jPanel1.add(abaixo_peso, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 200, -1, -1));

        obesidade_moderada.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 5.png"))); // NOI18N
        jPanel1.add(obesidade_moderada, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 210, -1, -1));

        obesidade_morbida.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Images/Group 6.png"))); // NOI18N
        jPanel1.add(obesidade_morbida, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 200, -1, -1));

        valorImc.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jPanel1.add(valorImc, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 250, 50));

        clean_btn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        clean_btn.setText("Limpar");
        clean_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clean_btnActionPerformed(evt);
            }
        });
        jPanel1.add(clean_btn, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 133, 290, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setSize(new java.awt.Dimension(737, 623));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void alturaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_alturaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_alturaActionPerformed

    private void pesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pesoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pesoActionPerformed

    private void calcular_imcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_calcular_imcActionPerformed
        Controller.CalcularImc_DAO.imc();
    }//GEN-LAST:event_calcular_imcActionPerformed

    private void closeBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closeBTNActionPerformed
        System.exit(0);
    }//GEN-LAST:event_closeBTNActionPerformed

    private void clean_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clean_btnActionPerformed
        Controller.CalcularImc_DAO.LimparTudo();
    }//GEN-LAST:event_clean_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio_GUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            new Inicio_GUI().setVisible(true);
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JLabel abaixo_peso;
    public static javax.swing.JTextField altura;
    private javax.swing.JButton calcular_imc;
    private javax.swing.JButton clean_btn;
    private javax.swing.JButton closeBTN;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    public static javax.swing.JLabel normal;
    public static javax.swing.JLabel obesidade_leve;
    public static javax.swing.JLabel obesidade_moderada;
    public static javax.swing.JLabel obesidade_morbida;
    public static javax.swing.JTextField peso;
    public static javax.swing.JLabel sobrepeso;
    public static javax.swing.JLabel valorImc;
    // End of variables declaration//GEN-END:variables
}
